version: "3.9"
services:
  ingress:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    entrypoint: /ingress
    command:
      - "-listen=:8080"
      - "-upstream-url=http://httpd:80"
  httpd:
    image: httpd
