apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-backend-nginx
data:
  default.conf: |
    server {
      listen 8443 ssl;
      server_name pass.localtest.me;

      ssl_certificate /etc/nginx/tls/tls.crt;
      ssl_certificate_key /etc/nginx/tls/tls.key;

      location / {
        add_header Content-Type text/plain;
        return 200 "hello from demo backend (tls)\n";
      }
    }
