apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress
  template:
    metadata:
      labels:
        app: ingress
    spec:
      serviceAccountName: ingress
      containers:
        - name: ingress
          image: ingress
          imagePullPolicy: IfNotPresent
          command:
            - /ingress
          args:
            - --instance=ingress1
            - --cert-mode=self-signed
          ports:
            - containerPort: 8443
              name: tls
