apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-dev

resources:
  - namespace.yaml
  - ingress-rbac.yaml
  - backend-configmap.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-http-configmap.yaml
  - backend-http-deployment.yaml
  - backend-http-service.yaml
  - backend-https-service.yaml
  - ingress-deployment.yaml
  - ingress-service.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: demo-backend-tls
    type: kubernetes.io/tls
    files:
      - tls.crt=certs/tls.crt
      - tls.key=certs/tls.key
